2021-04-21 12:24:07,180 ERROR 17452 nodejs.ClusterClientNoResponseError: client no response in 2075046ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (F:\workspace\Linux\abaabaaba\service\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 17452
hostname: LAPTOP-L5NQEC9V

2021-04-21 15:58:07,948 ERROR 17452 nodejs.ClusterClientNoResponseError: client no response in 3376994ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (F:\workspace\Linux\abaabaaba\service\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 17452
hostname: LAPTOP-L5NQEC9V

2021-04-21 18:22:23,437 ERROR 17452 nodejs.ClusterClientNoResponseError: client no response in 1302030ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (F:\workspace\Linux\abaabaaba\service\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 17452
hostname: LAPTOP-L5NQEC9V

2021-04-21 19:01:45,539 ERROR 4596 nodejs.ClusterClientNoResponseError: client no response in 708270ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (F:\workspace\Linux\abaabaaba\service\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 4596
hostname: LAPTOP-L5NQEC9V

2021-04-21 22:22:50,369 ERROR 20388 nodejs.ClusterClientNoResponseError: client no response in 1985424ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (F:\workspace\Linux\abaabaaba\service\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 20388
hostname: LAPTOP-L5NQEC9V

2021-04-22 04:27:27,570 ERROR 16024 nodejs.ClusterClientNoResponseError: client no response in 10799836ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (F:\workspace\Linux\abaabaaba\service\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 16024
hostname: LAPTOP-L5NQEC9V

2021-04-22 10:53:46,519 ERROR 16024 nodejs.ClusterClientNoResponseError: client no response in 23158910ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (F:\workspace\Linux\abaabaaba\service\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 16024
hostname: LAPTOP-L5NQEC9V

2021-04-22 13:56:11,445 ERROR 16024 nodejs.ClusterClientNoResponseError: client no response in 1239633ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (F:\workspace\Linux\abaabaaba\service\node_modules\cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 16024
hostname: LAPTOP-L5NQEC9V

